sudo: required
language: java
dist: mega
cache:
  directories:
  - $HOME/.cache/$TRAVIS_COMMIT
os:
- linux
- osx
branches:
  only:
  - master
notifications:
  email: true
script:
- ./make.sh travis build
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y wget unzip maven2 ".*-mingw-w64-.*" libgd2-xpm:i386 libgd2-xpm ia32-libs-multiarch ia32-libs build-essential gcc-multilib g++-multilib ;fi
- "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash ;fi"
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y git-lfs ;fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then  brew update  ;fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then  brew tap caskroom/cask ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then  brew install git-lfs ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then  brew install brew-cask ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then  brew cask install java ; fi
- git lfs install
after_success:
- ./make.sh travis deploy
env:
  global:
  - BINTRAY_USER: riccardo
  - secure: dpHuU/jCVjz+YYi3+HbLWJWgvARm0TE877I7A7lVQxHd4Bc3zv1MQ6yxdyHRtDB8wfrzWH+HK5buFivcitlScL6oczUsdq+Sq7GI+v5/SzbpPrsm5HVfRj1vJtIiSJ+4ek0LzBmvpXGshhv7JBjii8KmFA/0MsAckbn89HseZbOaLwQ+dEg4s+ZyzLD+adKH3/NrUr9BecbL4MMsZnNlSNQRBR99Hs+yX9K+wkLG8inS1zmmUqgnGF+7dk7nHyB5n+FnP/M04/CjqUc7lnBlG7Y6NgumBeL6+xwn5NQXSV1pNnZYSEWQM5kfdZcVjFKYUrwE6vY4l1pItiOJ480rYz46NhJQ3zTPmuBMmgaccPM4b74gBuPynvEmBW58qOqqdWYlKqup3BLpV4BvwGbLhIflj8lzo2ftV7BUvEJS3sXfYImRyguZ0MTV6q5dBqKD8TcgRWbSTfetCTbU7mB0ptAoJ+G7Qf+5ddEuiep5QxC0hdRrYZsD1DQDRR11Yqdvu7WsLuMkk1EeUPNCVK2i4Jcvdg3JXCd1d2O0Jgf2zZhOssWFsd8IxbDdVIMfZzZAIgKWs5lcvESupIIjX1QwfyoQLSYVqEvuMUX3M3GBTgR4+ul/RxcSXyl0oxOuWVCAuVuP/FvSeKcEIrkag0ArbszirXWG2N/v00oor+d8XiQ=
