sudo: required
language: java
dist: mega
cache:
  directories:
  - $HOME/.cache/$TRAVIS_COMMIT
os:
- linux
- osx
branches:
  only:
  - master
notifications:
  email: true
script:
- ./make.sh travis build
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y wget unzip maven2 ".*-mingw-w64-.*" libgd2-xpm:i386 libgd2-xpm ia32-libs-multiarch ia32-libs build-essential gcc-multilib g++-multilib ;fi
- "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash ;fi"
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y git-lfs ;fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then  brew update  ;fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then  brew tap caskroom/cask ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then  brew install git-lfs ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then  brew install brew-cask ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then  brew cask install java ; fi
- git lfs install
after_success:
- ./make.sh travis deploy
env:
  global:
  - BINTRAY_USER: riccardo
  - secure: "QHNovMOxhJDZcRonuvtMHal1HG59HpjAUp3RiRjw/E4YPcKZeP0MxMe40P2b7JzwzhTX2KqeTFzqCRVz9rAFQy7Pp4r+1adOn1uv9+Ce08t0A5P1VHc+Xk4ExfMyuHNxHRzVVOGxvf1y4Kc8m8MjUItNKQwVBhE5lqoX4i7qnhtFTkJlV/lMzUU4hVj1A6+7+2fuGNHrlhREbTplsitcVXf63DgZu0rtR/PldMs+CohQNQx7sSD8RuEdBRb3oVWAffyaILnlZ363DIZ2+0SmzXlX2aMkGjPcC6EJ65SDEl5NPRmEOcqkS8KJ8vpF0hWGH9PXrOdOT/ytnbAM15BK50hm3RNIuNXGOSz5ezUg8dtToDCwr23KDe60wI4cbBzOdFR3Q7rxV4EHhLYsYUsPnMT/++50DhWuEADJbZtCdTpvqCk/OCWHJyWhJMyDwXwUFj4ZFXyvKTXasDWaJkHY+U3za/9coB1no0cT/D6LkycC2CUWrVCG235enroxJP8ZQH7+/M8oY4MVISvfsKw1rQVVPZxtv4g9FODFUx9Rob1wcf2ym4328J+W35lz36YT4k4xC4ah363OKZegc2v/Wq5LqzAh25jhTQw5QZBepKwnEU6JLghCmn9T/b2chxY2g9ZGoXgKSAPWUNgpuXM8u4JE9P4JxwkRUORPjVspPag="